### ISSUE TITLE
issue while trying to insert a LaTeX environment

### ISSUE THREAD

**Issue by damienbelveze** [raineszm/obsidian-latex-environments#18] opened 2022-02-05 10:38 UTC
Hi, 

I have followed the instructions to install this plugin (both ways from Obsidian interface and by dezipping the plugin archive in the .plugin repository). 
I have checked more than twice I had activated the plugin, but when I try to insert a LaTeX environment between $$ and $$ nothing happen. The defined shortkey won't prompt a menu and the three commands (insert, change, delete environment) are not in the commands list.
Have I make an error somewhere ?
My Obsidian version is v.0.13

Thank you for your help,

Regards

Damien

**Comment by raineszm** [comment] 2022-02-10 14:45
This may be related to #17. Obsidian has switch from CodeMirror 5 to CodeMirror 6 in some cases. This plugin was originally written to interact with code mirror 5 so there are some incompatibilities. I'm working on a new release that should resolve the issue.

**Comment by raineszm** [comment] 2022-02-17 22:17
Duplicate of #17

**Closed by raineszm** 2022-02-17 22:17 UTC
